<template>
  <div class="px-base mt-10">
    <div class="flex justify-between mt-10">
      <h2 class="">Vietnam & Cambodia 2017</h2>
      <a class="button text-textColor" href="/">< return</a>
    </div>
    <ImageText v-for="item of photos" :image="item.path" :title="item.title" :text="item.text" :orientation="item.orientation"></ImageText>
    <div class="flex justify-end mb-8">
      <a class="button" href="/">< return</a>
    </div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';
  import ImageText from '@/components/ImageText.vue';

  export default defineComponent ({
    components: {
      ImageText
    },
    setup() {
    },
    data: () => ({
      photos: [{ path: '/images/photos/vietnam/01.jpg', orientation: 'landscape', title: 'Ho Chi Minh City, </br>Vietnam', text: 'I took this on the first day of our trip, and it has come to encapsulate my first and more lasting impressions of Saigon. The cables, the narrow colourful buildings, the inaccessible sidewalks, the incomprehensible excessive clothing of many local women (on 35 C with high humidity).'},
      { path: '/images/photos/vietnam/02.jpg', orientation: 'landscape', title: 'Ho Chi Minh City, </br>Vietnam', text: 'As we were walking around the city I was stopped by the woman on the left who insisted we should take a picture of her and the group. Seeing that, a group on the other side of the street asked me the same. Shortly after they all warned us to be careful of our cameras being stolen. Not a single word was exchanged in the process.'},
      { path: '/images/photos/vietnam/03.jpg', orientation: 'landscape', title: 'Ho Chi Minh City, </br>Vietnam', text: 'A late evening chat swimming in a pool overlooking a generic city. A bit earlier that day we were asked to remove our shoes as we walked in our much cheaper hotel, only to find a motorcycle parked next to the breakfast table; and a bit later that evening I would have to pass through a restaurant owner’s living room to wash my hands in a toilet, trying not to move their toothbrushes as I was getting some soap. So, this was the “richest” experience of the day. Also, the most generic. One that could unfold in any major city in the world.'},
      { path: '/images/photos/vietnam/04.jpg', orientation: 'landscape', title: 'Mekong Delta, </br>Vietnam', text: 'Each green speck is a plant grown individually to be sold to farmers. A single seed, grown in a tiny bit of soil, wrapped and kept in place by a banana leaf. Down the road there is a rice “factory” where people go with their sacks of rice to separate the grain (edible bit) from the hulls. The hulls are used for fire, and the ashes are used here as fertilizer. Nothing goes to waste.'},
      { path: '/images/photos/vietnam/05.jpg', orientation: 'landscape', title: 'Mekong Delta, </br>Vietnam', text: 'There was a lot of trash everywhere, including inside the yards and gardens of houses. Boats and houses were rarely painted, and decorative elements were almost entirely absent. But boats had a pair of eyes on the bow, and houses had pots of flowers.'},
      { path: '/images/photos/vietnam/06.jpg', orientation: 'landscape', title: 'Mekong Delta, </br>Vietnam', text: 'The separation between personal and professional lives in Vietnam is almost entirely absent. We witnessed cooking on the sidewalk in front of mechanic shops, washed our hands in a restaurant toilet complete with the owners’ toothbrushes, ate in a restaurant where someone was sleeping in a bed a couple of meters away, had to wait an offering ritual to finish before we could buy some clothes, bought groceries amidst a family meal, and had to walk through the owner’s bedroom on our way from the reception to our room. So, selling pineapples and doing your laundry in the back wasn’t so radical.'},
      { path: '/images/photos/vietnam/07.jpg', orientation: 'landscape', title: 'Mekong Delta, </br>Vietnam', text: 'The floating markets, just like the other markets, were devoid of shouting, advertising, or haggling. Sellers would advertise their products hanging them by a pole and then wait for buyers to arrive. Apart from fruit and vegetables that you could buy in their hundreds, you could also get sandwiches, soft drinks, coffee, petrol, and lottery tickets. Discards would go straight in the river.'},
      { path: '/images/photos/vietnam/08.jpg', orientation: 'landscape', title: 'Mekong Delta, </br>Vietnam', text: 'Knowing I would visit many poor and underdeveloped areas, in a romantic way, I was looking forward to traveling back in time, back in well established tradition. I was looking forward to traditional and elaborate craftmanship, in the boats, the clothing, the houses. Instead, what I saw wasn’t traditional, it was practical. People making a living with the limited resources they have. Rough made boats and houses, a lot of concrete, tin and metal, and older women wearing batman t-shirts. Of course I was fascinated. But I was also a little bit disappointed, and there is something very unfair about that.'},
      { path: '/images/photos/vietnam/09.jpg', orientation: 'landscape', title: 'Preah Vihear Province, </br>Cambodia', text: 'Amazingly, the local markets we visited were pretty quiet. No one was yelling trying to sell you things, which made walking and looking around much more enjoyable. It also allowed for relaxed interactions and moments like this.'},
      { path: '/images/photos/vietnam/10.jpg', orientation: 'landscape', title: 'Preah Vihear Province, </br>Cambodia', text: 'We spent a day in a very poor area in North Cambodia, visiting Mariagni’s colleagues working on humanitarian projects there. People have no electricity, running water, or toilets; little food, and big smiles. We had nothing to offer them, and yet a mother would instruct her daughter to pose for us when we felt like taking pictures. Same thing happened all over Vietnam. It’s as if every single person we met couldn’t wait to be in our photo album.'},
      { path: '/images/photos/vietnam/11.jpg', orientation: 'landscape', title: 'Angkor Wat, </br>Cambodia', text: 'It’s funny how sometimes you have to travel so far to celebrate something so common as a sunrise. If I have woken up to see the sunrise 7 times in my life, 5 of them were on this trip. This is one of them. Every day, hundreds of people gather here to see the sun rise behind the towers of Angkor Wat. If you think it was so spectacular, you are wrong. The photo is heavily processed.'},
      { path: '/images/photos/vietnam/12.jpg', orientation: 'landscape', title: 'Angkor Wat, </br>Cambodia', text: 'A monk providing a small bracelet and a blessing on a donation basis. As a greek person visiting an old buddhist temple in Cambodia, there was something sureal in leaving a couple of US dollars in his little basket'},
      { path: '/images/photos/vietnam/13.jpg', orientation: 'landscape', title: 'Angkor Wat, </br>Cambodia', text: 'I thought, she was posing for me. He thought she was posing for him. She thought, damn this is high.'},
      { path: '/images/photos/vietnam/14.jpg', orientation: 'landscape', title: 'Angkor Wat, </br>Cambodia', text: 'Among the visitors in the temple were Buddhist monks who like most of us were interested in exploring the site and taking a few pictures. I am still not sure why I found the image of a Buddhist monk, mobile phone in hand, snapping pictures, so intriguing. Is it because I have been taught that Buddhism denies material possessions, and therefore a monk holding a mobile phone seems like a paradox? Is it because I couldn’t imagine a Christian monk visiting and happily snapping pictures at a former site of worship? Probably a bit of both'},
      { path: '/images/photos/vietnam/15.jpg', orientation: 'landscape', title: 'Prasat Banteay Srei, </br>Cambodia', text: 'They call it the lady’s temple because of the elaborate carvings that obviously could not have been made by men (?). The carved surfaces resembled much more woodwork than a thousand-year-old carved sandstone, and apparently, the best preserved sections were the indoor ones, which were off limits for visitors. Our guide informed us that we were lucky to be here at that time of the day (quiet and shortly before close time) as the guardsman, who was standing impatiently nearby, could allow us in for a small fee. 10 minutes earlier, he was narrating that time in 2013 when 2 statues in the very same temple were found decapitated with the guards on duty disappeared. It was still unclear whether they cut off the heads to sell them, or as an act of revenge and frustration for not being able to make enough on the side like our unfortunate guardsman.'},
      { path: '/images/photos/vietnam/16.jpg', orientation: 'portrait', title: 'Ta Prohm, </br>Cambodia', text: 'We had just returned from a northern part of the country that just 10 years ago couldn’t be reached by car due to the thick jungle surrounding it. You had to ride a motorcycle, or take an airplane. Now, there were some young trees near the road but the jungle could barely be seen. For lunch we would stop in local restaurants and have 3$ worth of food sitting in thousands worth of solid wooden tables and chairs. We would hear stories of local people becoming rich by finding and selling a precious tree in the forest, or a rare animal. Authorities avoid moving the last few elephants, tigers and other animals in the national parks in fear of making them easier prey by advertising their location. Even here, in the world famous temples of Angkor, these trees might have only survived because of their low market value. My first emotional reaction was sadness for the forest, and animals but what about the people and their wish to make a better life for themselves? And isn’t depletion of resources and complete dominance over our environment the source of our western “wealth”? A wealth we popularise wherever we go'},
      { path: '/images/photos/vietnam/17.jpg', orientation: 'landscape', title: 'Angkor Thom, </br>Cambodia', text: 'We knew that walking on the old walls of Angkor Thom wasn’t in because we saw less than 10 people in a couple of hours of walking, most of them locals working in the area. But then, this appeared through the foliage. As a not well preserved specimen of five identical gates, this is not a must see, a road was never paved here, and it’s not part of any tourist itinerary. Bliss.'},
      { path: '/images/photos/vietnam/18.jpg', orientation: 'landscape', title: 'Tu Lan Cave System, </br>Vietnam', text: 'We were lucky enough to visit many caves, mostly of the enormous kind. The absence of paths and lights meant that we spent most of our time looking at our feet and battling with the surprising numbers of insects trying to take a closer look at our head torches and, as a side effect, our nostrils and mouths. Even looking up with our small head torches could not do justice to the vastness around us. But exits where magnificent.'},
      { path: '/images/photos/vietnam/19.jpg', orientation: 'landscape', title: 'Tu Lan Cave System, </br>Vietnam', text: 'Morning mist over the jungle. There was something magical waking up to this. Until you realised that the mist would not have allowed your clothes to dry so you would have to wear them wet.'},
      { path: '/images/photos/vietnam/20.jpg', orientation: 'landscape', title: 'Tu Lan Cave System, </br>Vietnam', text: 'Against my expectations, the caves were full of life. Bats, rats, frogs, spiders, countless flies and a lot of moss. There were also a lot of salt formations on the ceiling, which along with the moss where painting the caves in gold, silver, brown and green. Unfortunately, it was also dark so we only had a chance to have a good look near the exits.'},
      { path: '/images/photos/vietnam/21.jpg', orientation: 'landscape', title: 'Tu Lan Cave System, </br>Vietnam', text: 'Talking about Vietnam and its nature, one thing that is hard to explain is the scale of things. Hopefully this picture can help. Find the people chilling in the cave opening. Appreciate how big that opening is. Now look around at the vegetation, spot 1 or 2 big leaves and compare them to the people. Yes, really.'},
      { path: '/images/photos/vietnam/22.jpg', orientation: 'landscape', title: 'Hoi An, </br>Vietnam', text: 'On a typical touristic frenzy, we spent the first week waking up at 6am, traveling every day, and spending most of our waking hours struggling with tiredness. So, by the time we arrived in Hoi An, we were really looking forward to some down time. Luckily, on arrival, we faced this. Very touristic, yes, but in a “cultured” way. Very different from the touristic character of Siem Reap we had just left behind. Small crowded pedestrian alleys, instead of busy roads, interesting restaurants and cafes instead of burger joints and clubs, couples on wedding photo shoots instead of barkers. There was even a food festival with international chefs, with a Greek chef taking part. His signature dish was small pork skewers and greek salad. I hope he paid his plane ticket himself.'},
      { path: '/images/photos/vietnam/23.jpg', orientation: 'landscape', title: 'Hoi An, </br>Vietnam', text: 'Have you ever dreaded of leaving your job? Of starting an alternative lifestyle? Maybe starting you own business? What would it take? How about five plastic boxes and a bunch of fruit arrayed in front of your house?'},
      { path: '/images/photos/vietnam/24.jpg', orientation: 'landscape', title: 'Hoi An, </br>Vietnam', text: 'Chickens, ducks, geese, frogs, fish, crabs, prawns, turtles, starfish, all sold alive. Crabs were the only ones tied up with colourful bounds'},
      { path: '/images/photos/vietnam/25.jpg', orientation: 'landscape', title: 'Hoi An, </br>Vietnam', text: 'On a few occasions I was pretty puzzled by the communist state in Vietnam. Although officially declared an atheist State – you could see those stick and fruit offerings literally on every corner. On rural areas, we saw numerous graves built in the middle of farming plots – allegedly, so that the ancestor’s spirits will protect the family land. And much more concerningly, we heard multiple stories of people struggling to go through school and university because of how expensive education is – and yes this included primary and secondary school. Is this some weird Chinese whispers version of communism?'},
      { path: '/images/photos/vietnam/26.jpg', orientation: 'landscape', title: 'Thanh Ha, Hoi An, </br>Vietnam', text: 'Growing up in islandic Greece, small fishing boats were always bearers of pride for their owners, traditionally made with a high maintenance cost. Not so, in coastal Vietnam where boats were examples of practicality. Barren, with open hulls, and very often using glue instead of varnish or paint to protect their wood. We even saw small boats made out of concrete or in this case, plates of metal fitted around a wooden frame.'},
      { path: '/images/photos/vietnam/27.jpg', orientation: 'landscape', title: 'Cat Ba, </br>Vietnam', text: 'Between the lack of sleep, stomach bugs, and common colds we all struggled to climb that hill, and further struggled to relax in front of the view which we shared with a loud group of teenagers and music playing from nearby. I was even annoyed for not being able to see a proper sunset as the sun started disappearing at that high due to the cloudy weather. Now I look at it and all I see is beauty and serenity.'},
      { path: '/images/photos/vietnam/28.jpg', orientation: 'landscape', title: 'Lan Ha Bay, </br>Vietnam', text: 'When we were planning to spend a couple of days kayaking around Cat Ba island, we were envisioning lying in the sun for hours and swimming in blue lagoons. When we got there It was windy and slightly chilling. The sky was grey. The sea was brown and murky. Swimming was out of the question. But the beaches were beautiful and full of shellfish and broken coral.'},
      { path: '/images/photos/vietnam/29.jpg', orientation: 'landscape', title: 'Lan Ha Bay, </br>Vietnam', text: 'We saw a lot of similar baskets underwater, in swallow waters, seemingly filled with rocks. Were they storing more here for later use, or was this the nicest pile of garbage I’ve ever seen?'},
      { path: '/images/photos/vietnam/30.jpg', orientation: 'landscape', title: 'Lan Ha Bay, </br>Vietnam', text: 'A tiny house, a back yard made of empty barrels and nets holding fish, a satellite dish and three dogs to keep you company. We saw so many of those, some in bays by themselves, some gathered together in small villages. People would wave, dogs would bark, and children would repeatedly yell HELLOOO until we were out of sight.'},
      { path: '/images/photos/vietnam/31.jpg', orientation: 'portrait', title: 'Lan Ha Bay, </br>Vietnam', text: 'As far as sleeping is concerned I’ve met some pretty dedicated practitioners. But I have nothing but awe for the level of dedication the Vietnamese bring into play. I saw people sleeping on beds on a corner of a shop or restaurant. On hammocks hung from tuk-tuk’s and motorcycles or even inside the storage space of coaches. On small mats at the entrances of their shops or on the sidewalk under bridges (good shade). Even on benches or on the ground in front of their stalls during opening times. But this guy, wins sleeping.'},
      { path: '/images/photos/vietnam/32.jpg', orientation: 'landscape', title: 'Angkor Wat, </br>Vietnam', text: 'I want to thank these guys for sleeping on the floor of our only hotel room on our first night in Vietnam, for engaging in interesting conversations spanning from zero waste living to the commonality of pavement tiles, for eating unripe mangoes and other delicacies with me, for all the walking, trekking, swimming and kayaking, for sitting long hours on surprisingly comfortable and uncomfortable seats, including a 3h ride on small plastic stools in a bus’s aisle, for enduring my occasional moodiness, watching with me Chinese soap operas and Hollywood movies, calculating survival rates on taxi drives, playing 15s charades, and more importantly for convincing me and Mariagni to take this trip with them. You two are awesome.'},
      { path: '/images/photos/vietnam/33.jpg', orientation: 'landscape', title: 'Lan Ha Bay, </br>Vietnam', text: 'Thank you for guiding us to areas we would never have seen on our own, for getting us in touch with so interesting and nice people, for challenging me to get out of my comfort zone, putting up with my aversion of selfies, tolerating two straight days of Italian food, convincing me for that massage, killing all those cockroaches, sharing those beautiful views, posing with me for random locals and for always, always being there and taking care of me. Until the next one'},
      ]
    }),
    methods: {
      
    },
    computed: {
    },
    watch: {
    },
    mounted () {
    }
  })
</script>
